version: "3.8"

services:
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        restart: always
        environment:
            SPRING_DATASOURCE_URL: jdbc:mariadb://localhost:3306/smartwaste
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: 1234
        ports:
            - "3306:3306"
        volumes:
            - mariadb_data:/var/lib/mysql

volumes:
    mariadb_data:
