services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
      - 5000:5000
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/smartwaste
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: smartwaste
    ports:
      - 3307:3306
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
